// EDR gRPC service definitions.
// This is the primary interface between EDR agents and the control plane.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: agent.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegistrationRequest is sent by a new agent to enroll with the control plane.
type RegistrationRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	AgentId  string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os       string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch     string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Version  string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Commit   string                 `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"`
	// Agent capabilities advertised during registration.
	Capabilities []string `protobuf:"bytes,10,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Labels for policy targeting (e.g., "env:production", "dept:engineering").
	Labels        map[string]string `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegistrationRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegistrationRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegistrationRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegistrationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegistrationRequest) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *RegistrationRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegistrationRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// RegistrationResponse is returned by the control plane upon successful enrollment.
type RegistrationResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Accepted     bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AgentId      string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Message      string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatSec int32                  `protobuf:"varint,4,opt,name=heartbeat_sec,json=heartbeatSec,proto3" json:"heartbeat_sec,omitempty"`
	// Initial policy to apply before the first GetPolicy call.
	InitialPolicy *PolicyResponse `protobuf:"bytes,10,opt,name=initial_policy,json=initialPolicy,proto3" json:"initial_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegistrationResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegistrationResponse) GetHeartbeatSec() int32 {
	if x != nil {
		return x.HeartbeatSec
	}
	return 0
}

func (x *RegistrationResponse) GetInitialPolicy() *PolicyResponse {
	if x != nil {
		return x.InitialPolicy
	}
	return nil
}

// HeartbeatRequest is the periodic health report from an agent.
type HeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CpuPercent      float64                `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryMb        float64                `protobuf:"fixed64,6,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	EventsProcessed uint64                 `protobuf:"varint,7,opt,name=events_processed,json=eventsProcessed,proto3" json:"events_processed,omitempty"`
	AlertsGenerated uint64                 `protobuf:"varint,8,opt,name=alerts_generated,json=alertsGenerated,proto3" json:"alerts_generated,omitempty"`
	RulesLoaded     int32                  `protobuf:"varint,9,opt,name=rules_loaded,json=rulesLoaded,proto3" json:"rules_loaded,omitempty"`
	Isolated        bool                   `protobuf:"varint,10,opt,name=isolated,proto3" json:"isolated,omitempty"`
	UptimeSince     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=uptime_since,json=uptimeSince,proto3" json:"uptime_since,omitempty"`
	PolicyHash      string                 `protobuf:"bytes,12,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryMb() float64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *HeartbeatRequest) GetEventsProcessed() uint64 {
	if x != nil {
		return x.EventsProcessed
	}
	return 0
}

func (x *HeartbeatRequest) GetAlertsGenerated() uint64 {
	if x != nil {
		return x.AlertsGenerated
	}
	return 0
}

func (x *HeartbeatRequest) GetRulesLoaded() int32 {
	if x != nil {
		return x.RulesLoaded
	}
	return 0
}

func (x *HeartbeatRequest) GetIsolated() bool {
	if x != nil {
		return x.Isolated
	}
	return false
}

func (x *HeartbeatRequest) GetUptimeSince() *timestamppb.Timestamp {
	if x != nil {
		return x.UptimeSince
	}
	return nil
}

func (x *HeartbeatRequest) GetPolicyHash() string {
	if x != nil {
		return x.PolicyHash
	}
	return ""
}

// HeartbeatResponse carries any pending commands for the agent.
type HeartbeatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Accepted         bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	PendingCommands  []*Command             `protobuf:"bytes,2,rep,name=pending_commands,json=pendingCommands,proto3" json:"pending_commands,omitempty"`
	NextHeartbeatSec int32                  `protobuf:"varint,3,opt,name=next_heartbeat_sec,json=nextHeartbeatSec,proto3" json:"next_heartbeat_sec,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatResponse) GetPendingCommands() []*Command {
	if x != nil {
		return x.PendingCommands
	}
	return nil
}

func (x *HeartbeatResponse) GetNextHeartbeatSec() int32 {
	if x != nil {
		return x.NextHeartbeatSec
	}
	return 0
}

// PolicyRequest asks for the current policy for a specific agent.
type PolicyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CurrentPolicyHash string                 `protobuf:"bytes,2,opt,name=current_policy_hash,json=currentPolicyHash,proto3" json:"current_policy_hash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PolicyRequest) Reset() {
	*x = PolicyRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRequest) ProtoMessage() {}

func (x *PolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRequest.ProtoReflect.Descriptor instead.
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PolicyRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PolicyRequest) GetCurrentPolicyHash() string {
	if x != nil {
		return x.CurrentPolicyHash
	}
	return ""
}

// PolicyResponse contains the full detection and response policy.
type PolicyResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PolicyHash string                 `protobuf:"bytes,1,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	Changed    bool                   `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	// Detection configuration.
	Detection *DetectionPolicy `protobuf:"bytes,10,opt,name=detection,proto3" json:"detection,omitempty"`
	// Response configuration.
	Response *ResponsePolicy `protobuf:"bytes,11,opt,name=response,proto3" json:"response,omitempty"`
	// Rule bundles to apply.
	RuleBundles   []*RuleBundle `protobuf:"bytes,12,rep,name=rule_bundles,json=ruleBundles,proto3" json:"rule_bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyResponse) Reset() {
	*x = PolicyResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyResponse) ProtoMessage() {}

func (x *PolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyResponse.ProtoReflect.Descriptor instead.
func (*PolicyResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyResponse) GetPolicyHash() string {
	if x != nil {
		return x.PolicyHash
	}
	return ""
}

func (x *PolicyResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *PolicyResponse) GetDetection() *DetectionPolicy {
	if x != nil {
		return x.Detection
	}
	return nil
}

func (x *PolicyResponse) GetResponse() *ResponsePolicy {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PolicyResponse) GetRuleBundles() []*RuleBundle {
	if x != nil {
		return x.RuleBundles
	}
	return nil
}

// DetectionPolicy configures what the agent should detect.
type DetectionPolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SigmaEnabled      bool                   `protobuf:"varint,1,opt,name=sigma_enabled,json=sigmaEnabled,proto3" json:"sigma_enabled,omitempty"`
	YaraEnabled       bool                   `protobuf:"varint,2,opt,name=yara_enabled,json=yaraEnabled,proto3" json:"yara_enabled,omitempty"`
	IocEnabled        bool                   `protobuf:"varint,3,opt,name=ioc_enabled,json=iocEnabled,proto3" json:"ioc_enabled,omitempty"`
	BehavioralEnabled bool                   `protobuf:"varint,4,opt,name=behavioral_enabled,json=behavioralEnabled,proto3" json:"behavioral_enabled,omitempty"`
	SensitivityLevel  string                 `protobuf:"bytes,5,opt,name=sensitivity_level,json=sensitivityLevel,proto3" json:"sensitivity_level,omitempty"`
	RansomwareDetect  bool                   `protobuf:"varint,6,opt,name=ransomware_detect,json=ransomwareDetect,proto3" json:"ransomware_detect,omitempty"`
	RatDetect         bool                   `protobuf:"varint,7,opt,name=rat_detect,json=ratDetect,proto3" json:"rat_detect,omitempty"`
	ExfilDetect       bool                   `protobuf:"varint,8,opt,name=exfil_detect,json=exfilDetect,proto3" json:"exfil_detect,omitempty"`
	LateralDetect     bool                   `protobuf:"varint,9,opt,name=lateral_detect,json=lateralDetect,proto3" json:"lateral_detect,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DetectionPolicy) Reset() {
	*x = DetectionPolicy{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionPolicy) ProtoMessage() {}

func (x *DetectionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionPolicy.ProtoReflect.Descriptor instead.
func (*DetectionPolicy) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DetectionPolicy) GetSigmaEnabled() bool {
	if x != nil {
		return x.SigmaEnabled
	}
	return false
}

func (x *DetectionPolicy) GetYaraEnabled() bool {
	if x != nil {
		return x.YaraEnabled
	}
	return false
}

func (x *DetectionPolicy) GetIocEnabled() bool {
	if x != nil {
		return x.IocEnabled
	}
	return false
}

func (x *DetectionPolicy) GetBehavioralEnabled() bool {
	if x != nil {
		return x.BehavioralEnabled
	}
	return false
}

func (x *DetectionPolicy) GetSensitivityLevel() string {
	if x != nil {
		return x.SensitivityLevel
	}
	return ""
}

func (x *DetectionPolicy) GetRansomwareDetect() bool {
	if x != nil {
		return x.RansomwareDetect
	}
	return false
}

func (x *DetectionPolicy) GetRatDetect() bool {
	if x != nil {
		return x.RatDetect
	}
	return false
}

func (x *DetectionPolicy) GetExfilDetect() bool {
	if x != nil {
		return x.ExfilDetect
	}
	return false
}

func (x *DetectionPolicy) GetLateralDetect() bool {
	if x != nil {
		return x.LateralDetect
	}
	return false
}

// ResponsePolicy configures what automated actions the agent may take.
type ResponsePolicy struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AutoResponse        bool                   `protobuf:"varint,1,opt,name=auto_response,json=autoResponse,proto3" json:"auto_response,omitempty"`
	KillProcess         bool                   `protobuf:"varint,2,opt,name=kill_process,json=killProcess,proto3" json:"kill_process,omitempty"`
	QuarantineFile      bool                   `protobuf:"varint,3,opt,name=quarantine_file,json=quarantineFile,proto3" json:"quarantine_file,omitempty"`
	NetworkIsolate      bool                   `protobuf:"varint,4,opt,name=network_isolate,json=networkIsolate,proto3" json:"network_isolate,omitempty"`
	BlockHash           bool                   `protobuf:"varint,5,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	CollectForensics    bool                   `protobuf:"varint,6,opt,name=collect_forensics,json=collectForensics,proto3" json:"collect_forensics,omitempty"`
	KillOnCritical      bool                   `protobuf:"varint,7,opt,name=kill_on_critical,json=killOnCritical,proto3" json:"kill_on_critical,omitempty"`
	IsolateOnRansomware bool                   `protobuf:"varint,8,opt,name=isolate_on_ransomware,json=isolateOnRansomware,proto3" json:"isolate_on_ransomware,omitempty"`
	IsolateOnApt        bool                   `protobuf:"varint,9,opt,name=isolate_on_apt,json=isolateOnApt,proto3" json:"isolate_on_apt,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResponsePolicy) Reset() {
	*x = ResponsePolicy{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePolicy) ProtoMessage() {}

func (x *ResponsePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePolicy.ProtoReflect.Descriptor instead.
func (*ResponsePolicy) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ResponsePolicy) GetAutoResponse() bool {
	if x != nil {
		return x.AutoResponse
	}
	return false
}

func (x *ResponsePolicy) GetKillProcess() bool {
	if x != nil {
		return x.KillProcess
	}
	return false
}

func (x *ResponsePolicy) GetQuarantineFile() bool {
	if x != nil {
		return x.QuarantineFile
	}
	return false
}

func (x *ResponsePolicy) GetNetworkIsolate() bool {
	if x != nil {
		return x.NetworkIsolate
	}
	return false
}

func (x *ResponsePolicy) GetBlockHash() bool {
	if x != nil {
		return x.BlockHash
	}
	return false
}

func (x *ResponsePolicy) GetCollectForensics() bool {
	if x != nil {
		return x.CollectForensics
	}
	return false
}

func (x *ResponsePolicy) GetKillOnCritical() bool {
	if x != nil {
		return x.KillOnCritical
	}
	return false
}

func (x *ResponsePolicy) GetIsolateOnRansomware() bool {
	if x != nil {
		return x.IsolateOnRansomware
	}
	return false
}

func (x *ResponsePolicy) GetIsolateOnApt() bool {
	if x != nil {
		return x.IsolateOnApt
	}
	return false
}

// RuleBundle is a signed bundle of detection rules.
type RuleBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Hash          string                 `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleBundle) Reset() {
	*x = RuleBundle{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleBundle) ProtoMessage() {}

func (x *RuleBundle) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleBundle.ProtoReflect.Descriptor instead.
func (*RuleBundle) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RuleBundle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleBundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RuleBundle) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RuleBundle) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RuleBundle) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RuleBundle) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x03edr\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fevents.proto\x1a\falerts.proto\x1a\x0ecommands.proto\"\xbf\x02\n" +
	"\x13RegistrationRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x06 \x01(\tR\x06commit\x12\"\n" +
	"\fcapabilities\x18\n" +
	" \x03(\tR\fcapabilities\x12<\n" +
	"\x06labels\x18\v \x03(\v2$.edr.RegistrationRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\x01\n" +
	"\x14RegistrationResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rheartbeat_sec\x18\x04 \x01(\x05R\fheartbeatSec\x12:\n" +
	"\x0einitial_policy\x18\n" +
	" \x01(\v2\x13.edr.PolicyResponseR\rinitialPolicy\"\xcc\x03\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmemory_mb\x18\x06 \x01(\x01R\bmemoryMb\x12)\n" +
	"\x10events_processed\x18\a \x01(\x04R\x0feventsProcessed\x12)\n" +
	"\x10alerts_generated\x18\b \x01(\x04R\x0falertsGenerated\x12!\n" +
	"\frules_loaded\x18\t \x01(\x05R\vrulesLoaded\x12\x1a\n" +
	"\bisolated\x18\n" +
	" \x01(\bR\bisolated\x12=\n" +
	"\fuptime_since\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vuptimeSince\x12\x1f\n" +
	"\vpolicy_hash\x18\f \x01(\tR\n" +
	"policyHash\"\x96\x01\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x127\n" +
	"\x10pending_commands\x18\x02 \x03(\v2\f.edr.CommandR\x0fpendingCommands\x12,\n" +
	"\x12next_heartbeat_sec\x18\x03 \x01(\x05R\x10nextHeartbeatSec\"Z\n" +
	"\rPolicyRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12.\n" +
	"\x13current_policy_hash\x18\x02 \x01(\tR\x11currentPolicyHash\"\xe4\x01\n" +
	"\x0ePolicyResponse\x12\x1f\n" +
	"\vpolicy_hash\x18\x01 \x01(\tR\n" +
	"policyHash\x12\x18\n" +
	"\achanged\x18\x02 \x01(\bR\achanged\x122\n" +
	"\tdetection\x18\n" +
	" \x01(\v2\x14.edr.DetectionPolicyR\tdetection\x12/\n" +
	"\bresponse\x18\v \x01(\v2\x13.edr.ResponsePolicyR\bresponse\x122\n" +
	"\frule_bundles\x18\f \x03(\v2\x0f.edr.RuleBundleR\vruleBundles\"\xec\x02\n" +
	"\x0fDetectionPolicy\x12#\n" +
	"\rsigma_enabled\x18\x01 \x01(\bR\fsigmaEnabled\x12!\n" +
	"\fyara_enabled\x18\x02 \x01(\bR\vyaraEnabled\x12\x1f\n" +
	"\vioc_enabled\x18\x03 \x01(\bR\n" +
	"iocEnabled\x12-\n" +
	"\x12behavioral_enabled\x18\x04 \x01(\bR\x11behavioralEnabled\x12+\n" +
	"\x11sensitivity_level\x18\x05 \x01(\tR\x10sensitivityLevel\x12+\n" +
	"\x11ransomware_detect\x18\x06 \x01(\bR\x10ransomwareDetect\x12\x1d\n" +
	"\n" +
	"rat_detect\x18\a \x01(\bR\tratDetect\x12!\n" +
	"\fexfil_detect\x18\b \x01(\bR\vexfilDetect\x12%\n" +
	"\x0elateral_detect\x18\t \x01(\bR\rlateralDetect\"\xfa\x02\n" +
	"\x0eResponsePolicy\x12#\n" +
	"\rauto_response\x18\x01 \x01(\bR\fautoResponse\x12!\n" +
	"\fkill_process\x18\x02 \x01(\bR\vkillProcess\x12'\n" +
	"\x0fquarantine_file\x18\x03 \x01(\bR\x0equarantineFile\x12'\n" +
	"\x0fnetwork_isolate\x18\x04 \x01(\bR\x0enetworkIsolate\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x05 \x01(\bR\tblockHash\x12+\n" +
	"\x11collect_forensics\x18\x06 \x01(\bR\x10collectForensics\x12(\n" +
	"\x10kill_on_critical\x18\a \x01(\bR\x0ekillOnCritical\x122\n" +
	"\x15isolate_on_ransomware\x18\b \x01(\bR\x13isolateOnRansomware\x12$\n" +
	"\x0eisolate_on_apt\x18\t \x01(\bR\fisolateOnApt\"\x98\x01\n" +
	"\n" +
	"RuleBundle\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\tR\x04hash2\xd9\x02\n" +
	"\n" +
	"EDRService\x121\n" +
	"\fStreamEvents\x12\x0f.edr.EventBatch\x1a\f.edr.Command(\x010\x01\x12?\n" +
	"\bRegister\x12\x18.edr.RegistrationRequest\x1a\x19.edr.RegistrationResponse\x12:\n" +
	"\tHeartbeat\x12\x15.edr.HeartbeatRequest\x1a\x16.edr.HeartbeatResponse\x124\n" +
	"\tGetPolicy\x12\x12.edr.PolicyRequest\x1a\x13.edr.PolicyResponse\x12(\n" +
	"\vReportAlert\x12\n" +
	".edr.Alert\x1a\r.edr.AlertAck\x12;\n" +
	"\x0fUploadForensics\x12\x13.edr.ForensicsChunk\x1a\x11.edr.UploadResult(\x01B.Z,github.com/razatechofficial/edr/pkg/protocolb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_goTypes = []any{
	(*RegistrationRequest)(nil),   // 0: edr.RegistrationRequest
	(*RegistrationResponse)(nil),  // 1: edr.RegistrationResponse
	(*HeartbeatRequest)(nil),      // 2: edr.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 3: edr.HeartbeatResponse
	(*PolicyRequest)(nil),         // 4: edr.PolicyRequest
	(*PolicyResponse)(nil),        // 5: edr.PolicyResponse
	(*DetectionPolicy)(nil),       // 6: edr.DetectionPolicy
	(*ResponsePolicy)(nil),        // 7: edr.ResponsePolicy
	(*RuleBundle)(nil),            // 8: edr.RuleBundle
	nil,                           // 9: edr.RegistrationRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*Command)(nil),               // 11: edr.Command
	(*EventBatch)(nil),            // 12: edr.EventBatch
	(*Alert)(nil),                 // 13: edr.Alert
	(*ForensicsChunk)(nil),        // 14: edr.ForensicsChunk
	(*AlertAck)(nil),              // 15: edr.AlertAck
	(*UploadResult)(nil),          // 16: edr.UploadResult
}
var file_agent_proto_depIdxs = []int32{
	9,  // 0: edr.RegistrationRequest.labels:type_name -> edr.RegistrationRequest.LabelsEntry
	5,  // 1: edr.RegistrationResponse.initial_policy:type_name -> edr.PolicyResponse
	10, // 2: edr.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	10, // 3: edr.HeartbeatRequest.uptime_since:type_name -> google.protobuf.Timestamp
	11, // 4: edr.HeartbeatResponse.pending_commands:type_name -> edr.Command
	6,  // 5: edr.PolicyResponse.detection:type_name -> edr.DetectionPolicy
	7,  // 6: edr.PolicyResponse.response:type_name -> edr.ResponsePolicy
	8,  // 7: edr.PolicyResponse.rule_bundles:type_name -> edr.RuleBundle
	12, // 8: edr.EDRService.StreamEvents:input_type -> edr.EventBatch
	0,  // 9: edr.EDRService.Register:input_type -> edr.RegistrationRequest
	2,  // 10: edr.EDRService.Heartbeat:input_type -> edr.HeartbeatRequest
	4,  // 11: edr.EDRService.GetPolicy:input_type -> edr.PolicyRequest
	13, // 12: edr.EDRService.ReportAlert:input_type -> edr.Alert
	14, // 13: edr.EDRService.UploadForensics:input_type -> edr.ForensicsChunk
	11, // 14: edr.EDRService.StreamEvents:output_type -> edr.Command
	1,  // 15: edr.EDRService.Register:output_type -> edr.RegistrationResponse
	3,  // 16: edr.EDRService.Heartbeat:output_type -> edr.HeartbeatResponse
	5,  // 17: edr.EDRService.GetPolicy:output_type -> edr.PolicyResponse
	15, // 18: edr.EDRService.ReportAlert:output_type -> edr.AlertAck
	16, // 19: edr.EDRService.UploadForensics:output_type -> edr.UploadResult
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_events_proto_init()
	file_alerts_proto_init()
	file_commands_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
