// EDR gRPC service definitions.
// This is the primary interface between EDR agents and the control plane.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: agent.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EDRService_StreamEvents_FullMethodName    = "/edr.EDRService/StreamEvents"
	EDRService_Register_FullMethodName        = "/edr.EDRService/Register"
	EDRService_Heartbeat_FullMethodName       = "/edr.EDRService/Heartbeat"
	EDRService_GetPolicy_FullMethodName       = "/edr.EDRService/GetPolicy"
	EDRService_ReportAlert_FullMethodName     = "/edr.EDRService/ReportAlert"
	EDRService_UploadForensics_FullMethodName = "/edr.EDRService/UploadForensics"
)

// EDRServiceClient is the client API for EDRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EDRService is the bidirectional gRPC interface between EDR agents and
// the control plane server. Agents stream telemetry and alerts upstream,
// while the server pushes commands and policy updates downstream.
type EDRServiceClient interface {
	// StreamEvents establishes a bidirectional stream: the agent sends event
	// batches and receives commands (isolation, kill, scan, etc.) in return.
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventBatch, Command], error)
	// Register performs initial agent enrollment with the control plane.
	Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error)
	// Heartbeat sends periodic health reports and receives any pending commands.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// GetPolicy retrieves the current detection and response policy for this agent.
	GetPolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error)
	// ReportAlert sends a single high-priority alert for immediate processing.
	ReportAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*AlertAck, error)
	// UploadForensics streams forensic artifact data to the control plane.
	UploadForensics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ForensicsChunk, UploadResult], error)
}

type eDRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEDRServiceClient(cc grpc.ClientConnInterface) EDRServiceClient {
	return &eDRServiceClient{cc}
}

func (c *eDRServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventBatch, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EDRService_ServiceDesc.Streams[0], EDRService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventBatch, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EDRService_StreamEventsClient = grpc.BidiStreamingClient[EventBatch, Command]

func (c *eDRServiceClient) Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, EDRService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDRServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, EDRService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDRServiceClient) GetPolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyResponse)
	err := c.cc.Invoke(ctx, EDRService_GetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDRServiceClient) ReportAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*AlertAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertAck)
	err := c.cc.Invoke(ctx, EDRService_ReportAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDRServiceClient) UploadForensics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ForensicsChunk, UploadResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EDRService_ServiceDesc.Streams[1], EDRService_UploadForensics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ForensicsChunk, UploadResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EDRService_UploadForensicsClient = grpc.ClientStreamingClient[ForensicsChunk, UploadResult]

// EDRServiceServer is the server API for EDRService service.
// All implementations must embed UnimplementedEDRServiceServer
// for forward compatibility.
//
// EDRService is the bidirectional gRPC interface between EDR agents and
// the control plane server. Agents stream telemetry and alerts upstream,
// while the server pushes commands and policy updates downstream.
type EDRServiceServer interface {
	// StreamEvents establishes a bidirectional stream: the agent sends event
	// batches and receives commands (isolation, kill, scan, etc.) in return.
	StreamEvents(grpc.BidiStreamingServer[EventBatch, Command]) error
	// Register performs initial agent enrollment with the control plane.
	Register(context.Context, *RegistrationRequest) (*RegistrationResponse, error)
	// Heartbeat sends periodic health reports and receives any pending commands.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// GetPolicy retrieves the current detection and response policy for this agent.
	GetPolicy(context.Context, *PolicyRequest) (*PolicyResponse, error)
	// ReportAlert sends a single high-priority alert for immediate processing.
	ReportAlert(context.Context, *Alert) (*AlertAck, error)
	// UploadForensics streams forensic artifact data to the control plane.
	UploadForensics(grpc.ClientStreamingServer[ForensicsChunk, UploadResult]) error
	mustEmbedUnimplementedEDRServiceServer()
}

// UnimplementedEDRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEDRServiceServer struct{}

func (UnimplementedEDRServiceServer) StreamEvents(grpc.BidiStreamingServer[EventBatch, Command]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEDRServiceServer) Register(context.Context, *RegistrationRequest) (*RegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedEDRServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedEDRServiceServer) GetPolicy(context.Context, *PolicyRequest) (*PolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedEDRServiceServer) ReportAlert(context.Context, *Alert) (*AlertAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAlert not implemented")
}
func (UnimplementedEDRServiceServer) UploadForensics(grpc.ClientStreamingServer[ForensicsChunk, UploadResult]) error {
	return status.Error(codes.Unimplemented, "method UploadForensics not implemented")
}
func (UnimplementedEDRServiceServer) mustEmbedUnimplementedEDRServiceServer() {}
func (UnimplementedEDRServiceServer) testEmbeddedByValue()                    {}

// UnsafeEDRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EDRServiceServer will
// result in compilation errors.
type UnsafeEDRServiceServer interface {
	mustEmbedUnimplementedEDRServiceServer()
}

func RegisterEDRServiceServer(s grpc.ServiceRegistrar, srv EDRServiceServer) {
	// If the following call panics, it indicates UnimplementedEDRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EDRService_ServiceDesc, srv)
}

func _EDRService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EDRServiceServer).StreamEvents(&grpc.GenericServerStream[EventBatch, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EDRService_StreamEventsServer = grpc.BidiStreamingServer[EventBatch, Command]

func _EDRService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDRServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EDRService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDRServiceServer).Register(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDRService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDRServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EDRService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDRServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDRService_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDRServiceServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EDRService_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDRServiceServer).GetPolicy(ctx, req.(*PolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDRService_ReportAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Alert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDRServiceServer).ReportAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EDRService_ReportAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDRServiceServer).ReportAlert(ctx, req.(*Alert))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDRService_UploadForensics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EDRServiceServer).UploadForensics(&grpc.GenericServerStream[ForensicsChunk, UploadResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EDRService_UploadForensicsServer = grpc.ClientStreamingServer[ForensicsChunk, UploadResult]

// EDRService_ServiceDesc is the grpc.ServiceDesc for EDRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EDRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edr.EDRService",
	HandlerType: (*EDRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _EDRService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _EDRService_Heartbeat_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _EDRService_GetPolicy_Handler,
		},
		{
			MethodName: "ReportAlert",
			Handler:    _EDRService_ReportAlert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EDRService_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadForensics",
			Handler:       _EDRService_UploadForensics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
