// Alert definitions for the EDR detection pipeline.
// These types mirror the Go structs in internal/schema/alerts.go and
// pkg/events/types.go.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: alerts.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity represents the severity level of a detection alert.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_LOW         Severity = 2
	Severity_SEVERITY_MEDIUM      Severity = 3
	Severity_SEVERITY_HIGH        Severity = 4
	Severity_SEVERITY_CRITICAL    Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_LOW",
		3: "SEVERITY_MEDIUM",
		4: "SEVERITY_HIGH",
		5: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_LOW":         2,
		"SEVERITY_MEDIUM":      3,
		"SEVERITY_HIGH":        4,
		"SEVERITY_CRITICAL":    5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_alerts_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_alerts_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{0}
}

// MITREAttack represents a reference to a MITRE ATT&CK technique.
type MITREAttack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TechniqueId   string                 `protobuf:"bytes,1,opt,name=technique_id,json=techniqueId,proto3" json:"technique_id,omitempty"`
	TechniqueName string                 `protobuf:"bytes,2,opt,name=technique_name,json=techniqueName,proto3" json:"technique_name,omitempty"`
	TacticId      string                 `protobuf:"bytes,3,opt,name=tactic_id,json=tacticId,proto3" json:"tactic_id,omitempty"`
	TacticName    string                 `protobuf:"bytes,4,opt,name=tactic_name,json=tacticName,proto3" json:"tactic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MITREAttack) Reset() {
	*x = MITREAttack{}
	mi := &file_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MITREAttack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MITREAttack) ProtoMessage() {}

func (x *MITREAttack) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MITREAttack.ProtoReflect.Descriptor instead.
func (*MITREAttack) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *MITREAttack) GetTechniqueId() string {
	if x != nil {
		return x.TechniqueId
	}
	return ""
}

func (x *MITREAttack) GetTechniqueName() string {
	if x != nil {
		return x.TechniqueName
	}
	return ""
}

func (x *MITREAttack) GetTacticId() string {
	if x != nil {
		return x.TacticId
	}
	return ""
}

func (x *MITREAttack) GetTacticName() string {
	if x != nil {
		return x.TacticName
	}
	return ""
}

// Alert represents a detection alert generated by a rule engine.
type Alert struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AlertId     string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	RuleId      string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName    string                 `protobuf:"bytes,3,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	EndpointId  string                 `protobuf:"bytes,4,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Severity    Severity               `protobuf:"varint,5,opt,name=severity,proto3,enum=edr.Severity" json:"severity,omitempty"`
	Score       int32                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Title       string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Mitre       []*MITREAttack         `protobuf:"bytes,10,rep,name=mitre,proto3" json:"mitre,omitempty"`
	Tags        []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	// Process context from the triggering event.
	ProcessPid  int32  `protobuf:"varint,20,opt,name=process_pid,json=processPid,proto3" json:"process_pid,omitempty"`
	ProcessName string `protobuf:"bytes,21,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ProcessPath string `protobuf:"bytes,22,opt,name=process_path,json=processPath,proto3" json:"process_path,omitempty"`
	CommandLine string `protobuf:"bytes,23,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	// Raw event data for forensic purposes.
	RawEvent      []byte `protobuf:"bytes,30,opt,name=raw_event,json=rawEvent,proto3" json:"raw_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Alert) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *Alert) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *Alert) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Alert) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Alert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Alert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alert) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Alert) GetMitre() []*MITREAttack {
	if x != nil {
		return x.Mitre
	}
	return nil
}

func (x *Alert) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Alert) GetProcessPid() int32 {
	if x != nil {
		return x.ProcessPid
	}
	return 0
}

func (x *Alert) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *Alert) GetProcessPath() string {
	if x != nil {
		return x.ProcessPath
	}
	return ""
}

func (x *Alert) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *Alert) GetRawEvent() []byte {
	if x != nil {
		return x.RawEvent
	}
	return nil
}

// AlertAck is the server's acknowledgment of a received alert.
type AlertAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertAck) Reset() {
	*x = AlertAck{}
	mi := &file_alerts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertAck) ProtoMessage() {}

func (x *AlertAck) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertAck.ProtoReflect.Descriptor instead.
func (*AlertAck) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{2}
}

func (x *AlertAck) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AlertAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AlertAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AuditRecord represents an auditable action taken by the agent.
type AuditRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Outcome       string                 `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_alerts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{3}
}

func (x *AuditRecord) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AuditRecord) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *AuditRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditRecord) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *AuditRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuditRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_alerts_proto protoreflect.FileDescriptor

const file_alerts_proto_rawDesc = "" +
	"\n" +
	"\falerts.proto\x12\x03edr\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n" +
	"\vMITREAttack\x12!\n" +
	"\ftechnique_id\x18\x01 \x01(\tR\vtechniqueId\x12%\n" +
	"\x0etechnique_name\x18\x02 \x01(\tR\rtechniqueName\x12\x1b\n" +
	"\ttactic_id\x18\x03 \x01(\tR\btacticId\x12\x1f\n" +
	"\vtactic_name\x18\x04 \x01(\tR\n" +
	"tacticName\"\x8f\x04\n" +
	"\x05Alert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x03 \x01(\tR\bruleName\x12\x1f\n" +
	"\vendpoint_id\x18\x04 \x01(\tR\n" +
	"endpointId\x12)\n" +
	"\bseverity\x18\x05 \x01(\x0e2\r.edr.SeverityR\bseverity\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05score\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12&\n" +
	"\x05mitre\x18\n" +
	" \x03(\v2\x10.edr.MITREAttackR\x05mitre\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x1f\n" +
	"\vprocess_pid\x18\x14 \x01(\x05R\n" +
	"processPid\x12!\n" +
	"\fprocess_name\x18\x15 \x01(\tR\vprocessName\x12!\n" +
	"\fprocess_path\x18\x16 \x01(\tR\vprocessPath\x12!\n" +
	"\fcommand_line\x18\x17 \x01(\tR\vcommandLine\x12\x1b\n" +
	"\traw_event\x18\x1e \x01(\fR\brawEvent\"[\n" +
	"\bAlertAck\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd7\x01\n" +
	"\vAuditRecord\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*\x88\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x03\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x04\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x05B.Z,github.com/razatechofficial/edr/pkg/protocolb\x06proto3"

var (
	file_alerts_proto_rawDescOnce sync.Once
	file_alerts_proto_rawDescData []byte
)

func file_alerts_proto_rawDescGZIP() []byte {
	file_alerts_proto_rawDescOnce.Do(func() {
		file_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)))
	})
	return file_alerts_proto_rawDescData
}

var file_alerts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_alerts_proto_goTypes = []any{
	(Severity)(0),                 // 0: edr.Severity
	(*MITREAttack)(nil),           // 1: edr.MITREAttack
	(*Alert)(nil),                 // 2: edr.Alert
	(*AlertAck)(nil),              // 3: edr.AlertAck
	(*AuditRecord)(nil),           // 4: edr.AuditRecord
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_alerts_proto_depIdxs = []int32{
	0, // 0: edr.Alert.severity:type_name -> edr.Severity
	5, // 1: edr.Alert.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: edr.Alert.mitre:type_name -> edr.MITREAttack
	5, // 3: edr.AuditRecord.timestamp:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_alerts_proto_init() }
func file_alerts_proto_init() {
	if File_alerts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alerts_proto_goTypes,
		DependencyIndexes: file_alerts_proto_depIdxs,
		EnumInfos:         file_alerts_proto_enumTypes,
		MessageInfos:      file_alerts_proto_msgTypes,
	}.Build()
	File_alerts_proto = out.File
	file_alerts_proto_goTypes = nil
	file_alerts_proto_depIdxs = nil
}
