// Command and response definitions for the EDR control plane.
// These types mirror the Go structs in internal/schema/response.go.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: commands.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResponseAction enumerates the actions the control plane can instruct
// an agent to perform.
type ResponseAction int32

const (
	ResponseAction_RESPONSE_ACTION_UNSPECIFIED      ResponseAction = 0
	ResponseAction_RESPONSE_ACTION_KILL_PROCESS     ResponseAction = 1
	ResponseAction_RESPONSE_ACTION_QUARANTINE_FILE  ResponseAction = 2
	ResponseAction_RESPONSE_ACTION_HOST_ISOLATE     ResponseAction = 3
	ResponseAction_RESPONSE_ACTION_HOST_RELEASE     ResponseAction = 4
	ResponseAction_RESPONSE_ACTION_BLOCK_HASH       ResponseAction = 5
	ResponseAction_RESPONSE_ACTION_DISABLE_USER     ResponseAction = 6
	ResponseAction_RESPONSE_ACTION_COLLECT_FORENSIC ResponseAction = 7
	ResponseAction_RESPONSE_ACTION_TAKE_SNAPSHOT    ResponseAction = 8
	ResponseAction_RESPONSE_ACTION_UPDATE_RULES     ResponseAction = 9
	ResponseAction_RESPONSE_ACTION_UPDATE_CONFIG    ResponseAction = 10
	ResponseAction_RESPONSE_ACTION_SCAN_FILE        ResponseAction = 11
)

// Enum value maps for ResponseAction.
var (
	ResponseAction_name = map[int32]string{
		0:  "RESPONSE_ACTION_UNSPECIFIED",
		1:  "RESPONSE_ACTION_KILL_PROCESS",
		2:  "RESPONSE_ACTION_QUARANTINE_FILE",
		3:  "RESPONSE_ACTION_HOST_ISOLATE",
		4:  "RESPONSE_ACTION_HOST_RELEASE",
		5:  "RESPONSE_ACTION_BLOCK_HASH",
		6:  "RESPONSE_ACTION_DISABLE_USER",
		7:  "RESPONSE_ACTION_COLLECT_FORENSIC",
		8:  "RESPONSE_ACTION_TAKE_SNAPSHOT",
		9:  "RESPONSE_ACTION_UPDATE_RULES",
		10: "RESPONSE_ACTION_UPDATE_CONFIG",
		11: "RESPONSE_ACTION_SCAN_FILE",
	}
	ResponseAction_value = map[string]int32{
		"RESPONSE_ACTION_UNSPECIFIED":      0,
		"RESPONSE_ACTION_KILL_PROCESS":     1,
		"RESPONSE_ACTION_QUARANTINE_FILE":  2,
		"RESPONSE_ACTION_HOST_ISOLATE":     3,
		"RESPONSE_ACTION_HOST_RELEASE":     4,
		"RESPONSE_ACTION_BLOCK_HASH":       5,
		"RESPONSE_ACTION_DISABLE_USER":     6,
		"RESPONSE_ACTION_COLLECT_FORENSIC": 7,
		"RESPONSE_ACTION_TAKE_SNAPSHOT":    8,
		"RESPONSE_ACTION_UPDATE_RULES":     9,
		"RESPONSE_ACTION_UPDATE_CONFIG":    10,
		"RESPONSE_ACTION_SCAN_FILE":        11,
	}
)

func (x ResponseAction) Enum() *ResponseAction {
	p := new(ResponseAction)
	*p = x
	return p
}

func (x ResponseAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseAction) Descriptor() protoreflect.EnumDescriptor {
	return file_commands_proto_enumTypes[0].Descriptor()
}

func (ResponseAction) Type() protoreflect.EnumType {
	return &file_commands_proto_enumTypes[0]
}

func (x ResponseAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseAction.Descriptor instead.
func (ResponseAction) EnumDescriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

// Command represents an instruction from the control plane to an agent.
type Command struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CommandId   string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	EndpointId  string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Action      ResponseAction         `protobuf:"varint,3,opt,name=action,proto3,enum=edr.ResponseAction" json:"action,omitempty"`
	RequestedBy string                 `protobuf:"bytes,4,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	Reason      string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Nonce       string                 `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature   string                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	// Action-specific parameters.
	ProcessPid    int32  `protobuf:"varint,20,opt,name=process_pid,json=processPid,proto3" json:"process_pid,omitempty"`
	ProcessName   string `protobuf:"bytes,21,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	FilePath      string `protobuf:"bytes,22,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	HashValue     string `protobuf:"bytes,23,opt,name=hash_value,json=hashValue,proto3" json:"hash_value,omitempty"`
	Username      string `protobuf:"bytes,24,opt,name=username,proto3" json:"username,omitempty"`
	ConfigData    []byte `protobuf:"bytes,25,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *Command) GetAction() ResponseAction {
	if x != nil {
		return x.Action
	}
	return ResponseAction_RESPONSE_ACTION_UNSPECIFIED
}

func (x *Command) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *Command) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Command) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Command) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Command) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Command) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Command) GetProcessPid() int32 {
	if x != nil {
		return x.ProcessPid
	}
	return 0
}

func (x *Command) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *Command) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Command) GetHashValue() string {
	if x != nil {
		return x.HashValue
	}
	return ""
}

func (x *Command) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Command) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

// CommandResult reports the outcome of executing a command.
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Action        ResponseAction         `protobuf:"varint,3,opt,name=action,proto3,enum=edr.ResponseAction" json:"action,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ResultData    []byte                 `protobuf:"bytes,7,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *CommandResult) GetAction() ResponseAction {
	if x != nil {
		return x.Action
	}
	return ResponseAction_RESPONSE_ACTION_UNSPECIFIED
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CommandResult) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

// ForensicsChunk is a chunk of forensic data streamed from agent to server.
type ForensicsChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	ArtifactType  string                 `protobuf:"bytes,3,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	ArtifactName  string                 `protobuf:"bytes,4,opt,name=artifact_name,json=artifactName,proto3" json:"artifact_name,omitempty"`
	TotalSize     int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Offset        int64                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Sha256        string                 `protobuf:"bytes,8,opt,name=sha256,proto3" json:"sha256,omitempty"`
	FinalChunk    bool                   `protobuf:"varint,9,opt,name=final_chunk,json=finalChunk,proto3" json:"final_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForensicsChunk) Reset() {
	*x = ForensicsChunk{}
	mi := &file_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForensicsChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForensicsChunk) ProtoMessage() {}

func (x *ForensicsChunk) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForensicsChunk.ProtoReflect.Descriptor instead.
func (*ForensicsChunk) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{2}
}

func (x *ForensicsChunk) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ForensicsChunk) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ForensicsChunk) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *ForensicsChunk) GetArtifactName() string {
	if x != nil {
		return x.ArtifactName
	}
	return ""
}

func (x *ForensicsChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ForensicsChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ForensicsChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ForensicsChunk) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ForensicsChunk) GetFinalChunk() bool {
	if x != nil {
		return x.FinalChunk
	}
	return false
}

// UploadResult acknowledges receipt of a forensics upload stream.
type UploadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	BytesReceived int64                  `protobuf:"varint,4,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResult) Reset() {
	*x = UploadResult{}
	mi := &file_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResult) ProtoMessage() {}

func (x *UploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResult.ProtoReflect.Descriptor instead.
func (*UploadResult) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{3}
}

func (x *UploadResult) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *UploadResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadResult) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

var File_commands_proto protoreflect.FileDescriptor

const file_commands_proto_rawDesc = "" +
	"\n" +
	"\x0ecommands.proto\x12\x03edr\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x04\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12+\n" +
	"\x06action\x18\x03 \x01(\x0e2\x13.edr.ResponseActionR\x06action\x12!\n" +
	"\frequested_by\x18\x04 \x01(\tR\vrequestedBy\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x14\n" +
	"\x05nonce\x18\b \x01(\tR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\t \x01(\tR\tsignature\x12\x1f\n" +
	"\vprocess_pid\x18\x14 \x01(\x05R\n" +
	"processPid\x12!\n" +
	"\fprocess_name\x18\x15 \x01(\tR\vprocessName\x12\x1b\n" +
	"\tfile_path\x18\x16 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"hash_value\x18\x17 \x01(\tR\thashValue\x12\x1a\n" +
	"\busername\x18\x18 \x01(\tR\busername\x12\x1f\n" +
	"\vconfig_data\x18\x19 \x01(\fR\n" +
	"configData\"\x8b\x02\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12+\n" +
	"\x06action\x18\x03 \x01(\x0e2\x13.edr.ResponseActionR\x06action\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vresult_data\x18\a \x01(\fR\n" +
	"resultData\"\x9e\x02\n" +
	"\x0eForensicsChunk\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12#\n" +
	"\rartifact_type\x18\x03 \x01(\tR\fartifactType\x12#\n" +
	"\rartifact_name\x18\x04 \x01(\tR\fartifactName\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x12\x16\n" +
	"\x06sha256\x18\b \x01(\tR\x06sha256\x12\x1f\n" +
	"\vfinal_chunk\x18\t \x01(\bR\n" +
	"finalChunk\"\x8e\x01\n" +
	"\fUploadResult\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x0ebytes_received\x18\x04 \x01(\x03R\rbytesReceived*\xab\x03\n" +
	"\x0eResponseAction\x12\x1f\n" +
	"\x1bRESPONSE_ACTION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cRESPONSE_ACTION_KILL_PROCESS\x10\x01\x12#\n" +
	"\x1fRESPONSE_ACTION_QUARANTINE_FILE\x10\x02\x12 \n" +
	"\x1cRESPONSE_ACTION_HOST_ISOLATE\x10\x03\x12 \n" +
	"\x1cRESPONSE_ACTION_HOST_RELEASE\x10\x04\x12\x1e\n" +
	"\x1aRESPONSE_ACTION_BLOCK_HASH\x10\x05\x12 \n" +
	"\x1cRESPONSE_ACTION_DISABLE_USER\x10\x06\x12$\n" +
	" RESPONSE_ACTION_COLLECT_FORENSIC\x10\a\x12!\n" +
	"\x1dRESPONSE_ACTION_TAKE_SNAPSHOT\x10\b\x12 \n" +
	"\x1cRESPONSE_ACTION_UPDATE_RULES\x10\t\x12!\n" +
	"\x1dRESPONSE_ACTION_UPDATE_CONFIG\x10\n" +
	"\x12\x1d\n" +
	"\x19RESPONSE_ACTION_SCAN_FILE\x10\vB.Z,github.com/razatechofficial/edr/pkg/protocolb\x06proto3"

var (
	file_commands_proto_rawDescOnce sync.Once
	file_commands_proto_rawDescData []byte
)

func file_commands_proto_rawDescGZIP() []byte {
	file_commands_proto_rawDescOnce.Do(func() {
		file_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)))
	})
	return file_commands_proto_rawDescData
}

var file_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_commands_proto_goTypes = []any{
	(ResponseAction)(0),           // 0: edr.ResponseAction
	(*Command)(nil),               // 1: edr.Command
	(*CommandResult)(nil),         // 2: edr.CommandResult
	(*ForensicsChunk)(nil),        // 3: edr.ForensicsChunk
	(*UploadResult)(nil),          // 4: edr.UploadResult
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_commands_proto_depIdxs = []int32{
	0, // 0: edr.Command.action:type_name -> edr.ResponseAction
	5, // 1: edr.Command.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: edr.Command.expires_at:type_name -> google.protobuf.Timestamp
	0, // 3: edr.CommandResult.action:type_name -> edr.ResponseAction
	5, // 4: edr.CommandResult.timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_commands_proto_init() }
func file_commands_proto_init() {
	if File_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commands_proto_goTypes,
		DependencyIndexes: file_commands_proto_depIdxs,
		EnumInfos:         file_commands_proto_enumTypes,
		MessageInfos:      file_commands_proto_msgTypes,
	}.Build()
	File_commands_proto = out.File
	file_commands_proto_goTypes = nil
	file_commands_proto_depIdxs = nil
}
