// Event definitions for the EDR agent telemetry pipeline.
// These types mirror the Go structs in internal/schema/events.go and
// pkg/events/types.go for wire-format compatibility over gRPC.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: events.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType identifies the category of a kernel or system event.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_PROCESS     EventType = 1
	EventType_EVENT_TYPE_FILE        EventType = 2
	EventType_EVENT_TYPE_NETWORK     EventType = 3
	EventType_EVENT_TYPE_REGISTRY    EventType = 4
	EventType_EVENT_TYPE_MEMORY      EventType = 5
	EventType_EVENT_TYPE_DNS         EventType = 6
	EventType_EVENT_TYPE_AUTH        EventType = 7
	EventType_EVENT_TYPE_MODULE      EventType = 8
	EventType_EVENT_TYPE_MOUNT       EventType = 9
	EventType_EVENT_TYPE_PTRACE      EventType = 10
	EventType_EVENT_TYPE_SIGNAL      EventType = 11
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_PROCESS",
		2:  "EVENT_TYPE_FILE",
		3:  "EVENT_TYPE_NETWORK",
		4:  "EVENT_TYPE_REGISTRY",
		5:  "EVENT_TYPE_MEMORY",
		6:  "EVENT_TYPE_DNS",
		7:  "EVENT_TYPE_AUTH",
		8:  "EVENT_TYPE_MODULE",
		9:  "EVENT_TYPE_MOUNT",
		10: "EVENT_TYPE_PTRACE",
		11: "EVENT_TYPE_SIGNAL",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_PROCESS":     1,
		"EVENT_TYPE_FILE":        2,
		"EVENT_TYPE_NETWORK":     3,
		"EVENT_TYPE_REGISTRY":    4,
		"EVENT_TYPE_MEMORY":      5,
		"EVENT_TYPE_DNS":         6,
		"EVENT_TYPE_AUTH":        7,
		"EVENT_TYPE_MODULE":      8,
		"EVENT_TYPE_MOUNT":       9,
		"EVENT_TYPE_PTRACE":      10,
		"EVENT_TYPE_SIGNAL":      11,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

// BaseEvent contains fields common to all event types.
type BaseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventType     EventType              `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=edr.EventType" json:"event_type,omitempty"`
	EndpointId    string                 `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseEvent) Reset() {
	*x = BaseEvent{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEvent) ProtoMessage() {}

func (x *BaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseEvent.ProtoReflect.Descriptor instead.
func (*BaseEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *BaseEvent) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *BaseEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *BaseEvent) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *BaseEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BaseEvent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *BaseEvent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

// ProcessEvent represents a process creation, termination, or modification event.
type ProcessEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int32                  `protobuf:"varint,3,opt,name=ppid,proto3" json:"ppid,omitempty"`
	ParentName    string                 `protobuf:"bytes,4,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	ProcessName   string                 `protobuf:"bytes,5,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ProcessPath   string                 `protobuf:"bytes,6,opt,name=process_path,json=processPath,proto3" json:"process_path,omitempty"`
	CommandLine   string                 `protobuf:"bytes,7,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	User          string                 `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	Hashes        []string               `protobuf:"bytes,9,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent) Reset() {
	*x = ProcessEvent{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent) ProtoMessage() {}

func (x *ProcessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ProcessEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessEvent) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessEvent) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *ProcessEvent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *ProcessEvent) GetProcessPath() string {
	if x != nil {
		return x.ProcessPath
	}
	return ""
}

func (x *ProcessEvent) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *ProcessEvent) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessEvent) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

// FileEvent represents a file system operation event.
type FileEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	ActorPid      int32                  `protobuf:"varint,4,opt,name=actor_pid,json=actorPid,proto3" json:"actor_pid,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEvent) Reset() {
	*x = FileEvent{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent) ProtoMessage() {}

func (x *FileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent.ProtoReflect.Descriptor instead.
func (*FileEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *FileEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FileEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *FileEvent) GetActorPid() int32 {
	if x != nil {
		return x.ActorPid
	}
	return 0
}

func (x *FileEvent) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// NetworkEvent represents a network connection or communication event.
type NetworkEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SourceIp      string                 `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort    int32                  `protobuf:"varint,5,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestIp        string                 `protobuf:"bytes,6,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	DestPort      int32                  `protobuf:"varint,7,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Domain        string                 `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEvent) Reset() {
	*x = NetworkEvent{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEvent) ProtoMessage() {}

func (x *NetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEvent.ProtoReflect.Descriptor instead.
func (*NetworkEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *NetworkEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NetworkEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *NetworkEvent) GetSourcePort() int32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *NetworkEvent) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *NetworkEvent) GetDestPort() int32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *NetworkEvent) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// AuthEvent represents an authentication event.
type AuthEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Outcome       string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	AuthType      string                 `protobuf:"bytes,4,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	SourceIp      string                 `protobuf:"bytes,5,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthEvent) Reset() {
	*x = AuthEvent{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEvent) ProtoMessage() {}

func (x *AuthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEvent.ProtoReflect.Descriptor instead.
func (*AuthEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *AuthEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *AuthEvent) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AuthEvent) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *AuthEvent) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *AuthEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AuthEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// DNSEvent represents a DNS query/response event.
type DNSEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	QueryName     string                 `protobuf:"bytes,3,opt,name=query_name,json=queryName,proto3" json:"query_name,omitempty"`
	QueryType     string                 `protobuf:"bytes,4,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	Answers       []string               `protobuf:"bytes,5,rep,name=answers,proto3" json:"answers,omitempty"`
	ResponseCode  string                 `protobuf:"bytes,6,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSEvent) Reset() {
	*x = DNSEvent{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSEvent) ProtoMessage() {}

func (x *DNSEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSEvent.ProtoReflect.Descriptor instead.
func (*DNSEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *DNSEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DNSEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DNSEvent) GetQueryName() string {
	if x != nil {
		return x.QueryName
	}
	return ""
}

func (x *DNSEvent) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *DNSEvent) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *DNSEvent) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

// RegistryEvent represents a Windows registry operation.
type RegistryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseEvent             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	KeyPath       string                 `protobuf:"bytes,3,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	ValueName     string                 `protobuf:"bytes,4,opt,name=value_name,json=valueName,proto3" json:"value_name,omitempty"`
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryEvent) Reset() {
	*x = RegistryEvent{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryEvent) ProtoMessage() {}

func (x *RegistryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryEvent.ProtoReflect.Descriptor instead.
func (*RegistryEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *RegistryEvent) GetBase() *BaseEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RegistryEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RegistryEvent) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *RegistryEvent) GetValueName() string {
	if x != nil {
		return x.ValueName
	}
	return ""
}

func (x *RegistryEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *RegistryEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// EventBatch holds a batch of events for efficient streaming to the control plane.
type EventBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BatchTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=batch_time,json=batchTime,proto3" json:"batch_time,omitempty"`
	Sequence       int32                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ProcessEvents  []*ProcessEvent        `protobuf:"bytes,10,rep,name=process_events,json=processEvents,proto3" json:"process_events,omitempty"`
	FileEvents     []*FileEvent           `protobuf:"bytes,11,rep,name=file_events,json=fileEvents,proto3" json:"file_events,omitempty"`
	NetworkEvents  []*NetworkEvent        `protobuf:"bytes,12,rep,name=network_events,json=networkEvents,proto3" json:"network_events,omitempty"`
	AuthEvents     []*AuthEvent           `protobuf:"bytes,13,rep,name=auth_events,json=authEvents,proto3" json:"auth_events,omitempty"`
	DnsEvents      []*DNSEvent            `protobuf:"bytes,14,rep,name=dns_events,json=dnsEvents,proto3" json:"dns_events,omitempty"`
	RegistryEvents []*RegistryEvent       `protobuf:"bytes,15,rep,name=registry_events,json=registryEvents,proto3" json:"registry_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *EventBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventBatch) GetBatchTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BatchTime
	}
	return nil
}

func (x *EventBatch) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EventBatch) GetProcessEvents() []*ProcessEvent {
	if x != nil {
		return x.ProcessEvents
	}
	return nil
}

func (x *EventBatch) GetFileEvents() []*FileEvent {
	if x != nil {
		return x.FileEvents
	}
	return nil
}

func (x *EventBatch) GetNetworkEvents() []*NetworkEvent {
	if x != nil {
		return x.NetworkEvents
	}
	return nil
}

func (x *EventBatch) GetAuthEvents() []*AuthEvent {
	if x != nil {
		return x.AuthEvents
	}
	return nil
}

func (x *EventBatch) GetDnsEvents() []*DNSEvent {
	if x != nil {
		return x.DnsEvents
	}
	return nil
}

func (x *EventBatch) GetRegistryEvents() []*RegistryEvent {
	if x != nil {
		return x.RegistryEvents
	}
	return nil
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x03edr\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\tBaseEvent\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12-\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x0e.edr.EventTypeR\teventType\x12\x1f\n" +
	"\vendpoint_id\x18\x03 \x01(\tR\n" +
	"endpointId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\"\x8e\x02\n" +
	"\fProcessEvent\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.edr.BaseEventR\x04base\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x03 \x01(\x05R\x04ppid\x12\x1f\n" +
	"\vparent_name\x18\x04 \x01(\tR\n" +
	"parentName\x12!\n" +
	"\fprocess_name\x18\x05 \x01(\tR\vprocessName\x12!\n" +
	"\fprocess_path\x18\x06 \x01(\tR\vprocessPath\x12!\n" +
	"\fcommand_line\x18\a \x01(\tR\vcommandLine\x12\x12\n" +
	"\x04user\x18\b \x01(\tR\x04user\x12\x16\n" +
	"\x06hashes\x18\t \x03(\tR\x06hashes\"\x92\x01\n" +
	"\tFileEvent\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.edr.BaseEventR\x04base\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x1b\n" +
	"\tactor_pid\x18\x04 \x01(\x05R\bactorPid\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\"\xec\x01\n" +
	"\fNetworkEvent\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.edr.BaseEventR\x04base\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\x04 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x05 \x01(\x05R\n" +
	"sourcePort\x12\x17\n" +
	"\adest_ip\x18\x06 \x01(\tR\x06destIp\x12\x1b\n" +
	"\tdest_port\x18\a \x01(\x05R\bdestPort\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\"\xb6\x01\n" +
	"\tAuthEvent\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.edr.BaseEventR\x04base\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12\x1b\n" +
	"\tauth_type\x18\x04 \x01(\tR\bauthType\x12\x1b\n" +
	"\tsource_ip\x18\x05 \x01(\tR\bsourceIp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"\xbd\x01\n" +
	"\bDNSEvent\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.edr.BaseEventR\x04base\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"query_name\x18\x03 \x01(\tR\tqueryName\x12\x1d\n" +
	"\n" +
	"query_type\x18\x04 \x01(\tR\tqueryType\x12\x18\n" +
	"\aanswers\x18\x05 \x03(\tR\aanswers\x12#\n" +
	"\rresponse_code\x18\x06 \x01(\tR\fresponseCode\"\xb1\x01\n" +
	"\rRegistryEvent\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.edr.BaseEventR\x04base\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x19\n" +
	"\bkey_path\x18\x03 \x01(\tR\akeyPath\x12\x1d\n" +
	"\n" +
	"value_name\x18\x04 \x01(\tR\tvalueName\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\xbf\x03\n" +
	"\n" +
	"EventBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x129\n" +
	"\n" +
	"batch_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tbatchTime\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x05R\bsequence\x128\n" +
	"\x0eprocess_events\x18\n" +
	" \x03(\v2\x11.edr.ProcessEventR\rprocessEvents\x12/\n" +
	"\vfile_events\x18\v \x03(\v2\x0e.edr.FileEventR\n" +
	"fileEvents\x128\n" +
	"\x0enetwork_events\x18\f \x03(\v2\x11.edr.NetworkEventR\rnetworkEvents\x12/\n" +
	"\vauth_events\x18\r \x03(\v2\x0e.edr.AuthEventR\n" +
	"authEvents\x12,\n" +
	"\n" +
	"dns_events\x18\x0e \x03(\v2\r.edr.DNSEventR\tdnsEvents\x12;\n" +
	"\x0fregistry_events\x18\x0f \x03(\v2\x12.edr.RegistryEventR\x0eregistryEvents*\xa0\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_PROCESS\x10\x01\x12\x13\n" +
	"\x0fEVENT_TYPE_FILE\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_NETWORK\x10\x03\x12\x17\n" +
	"\x13EVENT_TYPE_REGISTRY\x10\x04\x12\x15\n" +
	"\x11EVENT_TYPE_MEMORY\x10\x05\x12\x12\n" +
	"\x0eEVENT_TYPE_DNS\x10\x06\x12\x13\n" +
	"\x0fEVENT_TYPE_AUTH\x10\a\x12\x15\n" +
	"\x11EVENT_TYPE_MODULE\x10\b\x12\x14\n" +
	"\x10EVENT_TYPE_MOUNT\x10\t\x12\x15\n" +
	"\x11EVENT_TYPE_PTRACE\x10\n" +
	"\x12\x15\n" +
	"\x11EVENT_TYPE_SIGNAL\x10\vB.Z,github.com/razatechofficial/edr/pkg/protocolb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_events_proto_goTypes = []any{
	(EventType)(0),                // 0: edr.EventType
	(*BaseEvent)(nil),             // 1: edr.BaseEvent
	(*ProcessEvent)(nil),          // 2: edr.ProcessEvent
	(*FileEvent)(nil),             // 3: edr.FileEvent
	(*NetworkEvent)(nil),          // 4: edr.NetworkEvent
	(*AuthEvent)(nil),             // 5: edr.AuthEvent
	(*DNSEvent)(nil),              // 6: edr.DNSEvent
	(*RegistryEvent)(nil),         // 7: edr.RegistryEvent
	(*EventBatch)(nil),            // 8: edr.EventBatch
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_events_proto_depIdxs = []int32{
	0,  // 0: edr.BaseEvent.event_type:type_name -> edr.EventType
	9,  // 1: edr.BaseEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 2: edr.ProcessEvent.base:type_name -> edr.BaseEvent
	1,  // 3: edr.FileEvent.base:type_name -> edr.BaseEvent
	1,  // 4: edr.NetworkEvent.base:type_name -> edr.BaseEvent
	1,  // 5: edr.AuthEvent.base:type_name -> edr.BaseEvent
	1,  // 6: edr.DNSEvent.base:type_name -> edr.BaseEvent
	1,  // 7: edr.RegistryEvent.base:type_name -> edr.BaseEvent
	9,  // 8: edr.EventBatch.batch_time:type_name -> google.protobuf.Timestamp
	2,  // 9: edr.EventBatch.process_events:type_name -> edr.ProcessEvent
	3,  // 10: edr.EventBatch.file_events:type_name -> edr.FileEvent
	4,  // 11: edr.EventBatch.network_events:type_name -> edr.NetworkEvent
	5,  // 12: edr.EventBatch.auth_events:type_name -> edr.AuthEvent
	6,  // 13: edr.EventBatch.dns_events:type_name -> edr.DNSEvent
	7,  // 14: edr.EventBatch.registry_events:type_name -> edr.RegistryEvent
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
