package events

import "time"

// EventType identifies the category of a kernel or system event.
type EventType string

const (
	EventProcess  EventType = "process"
	EventFile     EventType = "file"
	EventNetwork  EventType = "network"
	EventRegistry EventType = "registry"
	EventMemory   EventType = "memory"
	EventDNS      EventType = "dns"
	EventAuth     EventType = "auth"
	EventModule   EventType = "module"
	EventMount    EventType = "mount"
	EventPtrace   EventType = "ptrace"
	EventSignal   EventType = "signal"
)

// Severity represents the severity level of a detection alert.
type Severity string

const (
	SeverityInfo     Severity = "info"
	SeverityLow      Severity = "low"
	SeverityMedium   Severity = "medium"
	SeverityHigh     Severity = "high"
	SeverityCritical Severity = "critical"
)

// MITREAttack represents a reference to a MITRE ATT&CK technique and its parent tactic.
type MITREAttack struct {
	TechniqueID   string `json:"technique_id" yaml:"technique_id"`
	TechniqueName string `json:"technique_name" yaml:"technique_name"`
	TacticID      string `json:"tactic_id" yaml:"tactic_id"`
	TacticName    string `json:"tactic_name" yaml:"tactic_name"`
}

// Alert represents a detection alert generated by a rule engine.
type Alert struct {
	ID          string        `json:"id"`
	RuleID      string        `json:"rule_id"`
	RuleName    string        `json:"rule_name"`
	Severity    Severity      `json:"severity"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Timestamp   time.Time     `json:"timestamp"`
	MITRE       []MITREAttack `json:"mitre,omitempty"`
	Tags        []string      `json:"tags,omitempty"`
	RawEvent    interface{}   `json:"raw_event,omitempty"`
}
