package events

import "time"

// EventType identifies the category of a kernel or system event.
type EventType string

const (
	EventProcess    EventType = "process"
	EventFile       EventType = "file"
	EventNetwork    EventType = "network"
	EventRegistry   EventType = "registry"
	EventMemory     EventType = "memory"
	EventDNS        EventType = "dns"
	EventAuth       EventType = "auth"
	EventModule     EventType = "module"
	EventMount      EventType = "mount"
	EventPtrace     EventType = "ptrace"
	EventSignal     EventType = "signal"
	EventWMI        EventType = "wmi"
	EventPowerShell EventType = "powershell"
	EventPipe       EventType = "pipe"
	EventBITS       EventType = "bits"
	EventTask       EventType = "task"
	EventNamespace  EventType = "namespace"
	// EventSecurity groups AMSI, Code Integrity, AppLocker, and Defender ETW streams.
	EventSecurity EventType = "security"
)

// Severity represents the severity level of a detection alert.
type Severity string

const (
	SeverityInfo     Severity = "info"
	SeverityLow      Severity = "low"
	SeverityMedium   Severity = "medium"
	SeverityHigh     Severity = "high"
	SeverityCritical Severity = "critical"
)

// MITREAttack represents a reference to a MITRE ATT&CK technique and its parent tactic.
type MITREAttack struct {
	TechniqueID   string `json:"technique_id" yaml:"technique_id"`
	TechniqueName string `json:"technique_name" yaml:"technique_name"`
	TacticID      string `json:"tactic_id" yaml:"tactic_id"`
	TacticName    string `json:"tactic_name" yaml:"tactic_name"`
}

// ProcessExecEvent represents a process execution event from the kernel driver.
type ProcessExecEvent struct {
	Timestamp   time.Time `json:"timestamp"`
	PID         uint32    `json:"pid"`
	PPID        uint32    `json:"ppid"`
	ProcessName string    `json:"process_name"`
	ProcessPath string    `json:"process_path"`
	CommandLine string    `json:"command_line"`
	User        string    `json:"user,omitempty"`
	Hashes      []string  `json:"hashes,omitempty"`
}

// FileWriteEvent represents a file write event from the kernel driver.
type FileWriteEvent struct {
	Timestamp    time.Time `json:"timestamp"`
	PID          uint32    `json:"pid"`
	Path         string    `json:"path"`
	BytesWritten uint64    `json:"bytes_written"`
	Entropy      float64   `json:"entropy"`
}

// NetworkConnectEvent represents an outbound network connection event.
type NetworkConnectEvent struct {
	Timestamp time.Time `json:"timestamp"`
	PID       uint32    `json:"pid"`
	DstAddr   string    `json:"dst_addr"`
	DstPort   uint16    `json:"dst_port"`
	Protocol  string    `json:"protocol"`
}

// Alert represents a detection alert generated by a rule engine.
type Alert struct {
	ID          string        `json:"id"`
	RuleID      string        `json:"rule_id"`
	RuleName    string        `json:"rule_name"`
	Severity    Severity      `json:"severity"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Timestamp   time.Time     `json:"timestamp"`
	MITRE       []MITREAttack `json:"mitre,omitempty"`
	Tags        []string      `json:"tags,omitempty"`
	RawEvent    interface{}   `json:"raw_event,omitempty"`

	// File context (e.g. YARA file scan). Populated when the detection has a path/hash.
	FilePath   string `json:"file_path,omitempty"`
	FileSHA256 string `json:"file_sha256,omitempty"`
}
